image: node:8.4

pipelines:
  default:
    - step:
        name: setup
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm set registry https://knab-npm.ddns.net
          - npm set strict-ssl false
    - step:
        name: install
        script:
          - npm install
    - step:
        name: build
        script:
          - npm run build
    - step:
        name: test
        script:
          - npm run test
