image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm set registry https://knab-npm.ddns.net
          - npm set strict-ssl false
          - npm install
          - npm run build
          - npm run test
