image: node:8.4

pipelines:
  default:
    - step:
        name: Test and build
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm set registry https://registry.npmjs.org
          - npm config set @knx:registry=https://npm.mgmt.a-random-domain.com/
          - npm config set @cx:registry=https://npm.mgmt.a-random-domain.com/
          - npm set strict-ssl false
          - npm install
          - npm run lint:styles
          - npm run lint
          - npm run test:ci
          - npm run build
