image: node:8.4

pipelines:
  default:
    - step:
        name: Test and build
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm set registry https://knab-npm.ddns.net
          - npm set strict-ssl false
          - npm install
          - npm update
          - npm run test:ci
          - npm run build
