import { Car } from '../car';

export const mockCar: Car = {
  'license': 'KG906T',
  'vin': 'VF1BA0F0G17869206',
  'reporting_code': '9206',
  'year': 2016,
  'fuel': 'Gasoline',
  'secondary_fuel': null,
  'color': 'Blauw',
  'color_code': '04',
  'secondary_color': 'Onbekend',
  'secondary_color_code': '99',
  'weight_empty_vehicle': 1030,
  'price_consumer_excl_vat': 14841,
  'price_consumer_incl_vat': 16976,
  'make': 'RENAULT',
  'model': 'MEGANE',
  'technical_type': '1.6 E HB RT',
  'wheels': 4,
  'top_speed': 184,
  'engine_capacity': 1598,
  'power_kw': 66,
  'transmission': 'Manual',
  'transmission_nl': 'Handgeschakeld',
  'edition': '1.9 TDI',
  'doors': 5,
};
