#!/usr/bin/env bash

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep -q "$1"
	if [ $? -eq 0  ]; then
      eval "$2"
  fi
}

check_run package.json "npm prune && npm install"
